name: anonity
description: "Anonity — Speak freely. Stay anonymous."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.0
  dynamic_color: ^1.8.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/g.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
